config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup' => 'farmers#new' # change to follow \signup path for new farmer
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :farmers
  resources :activities, only: [:create, :destroy, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if @activity.nil?
      @activity = current_farmer.activities.build if logged_in?
    end
    if logged_in?
      @feed_items = current_farmer.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in_home.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="farmer_info">
      <%= render 'shared/farmer_info' %>
    </section>
    <section class="activity_form">
      <%= render 'shared/activity_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Activity Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/_not_logged_in_home.html.erb
<div class="center jumbotron">
  <h1>Sample app</h1>
  <h2>
    <a href="https://app.farmeron.com"><em>Farmeron App</em></a>
     farmer's best and only friend.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
	<%= render 'logged_in_home' %>
<% else %>
	<%= render 'not_logged_in_home' %>
<% end %>