config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup' => 'farmers#new' # change to follow \signup path for new farmer
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :farmers
  resources :activities, only: [:create, :destroy, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :farmer

  validates :farmer_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  validates :activity_date, presence: true
  default_scope { order(activity_date: :desc) }

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :logged_in_farmer, only: [:edit, :create, :destroy, :update]
  before_action :correct_farmer, only: [:edit, :destroy, :update]

  def create
    @activity = current_farmer.activities.build(activity_params)
    if @activity.save
      flash[:success] = "Activity created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @activity.destroy
    flash[:success] = "Scheduled activity deleted"
    redirect_to request.referrer || root_url
  end

  def edit
    store_location_referrer
    @activity = current_farmer.activities.find_by(id: params[:id])
  end

  def update
    @activity = current_farmer.activities.find_by(id: params[:id])
    if @activity.update_attributes(activity_params)
      flash[:success] = "Activity updated"
      redirect_way_back_or(root_url)
    else
      flash[:danger] = "Activity not updated"
    end
  end

  private

    def activity_params
      params.require(:activity).permit(:content, :activity_date,
                                        :farmer_id, :public, :active)
    end

    def correct_farmer
      @activity = current_farmer.activities.find_by(id: params[:id])
      redirect_to root_url if @activity.nil?
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<li id="activity-<%= activity.id %>">
  <%= link_to gravatar_for(activity.farmer, size: 50), activity.farmer %>
  <span class="farmer"><%= link_to activity.farmer.name, activity.farmer %></span>
  <span class="content"><%= activity.content %></span>
  <span class="timestamp">
    Scheduled date: <%= activity.activity_date.to_formatted_s(:short) %>.
    <% if current_farmer?(activity.farmer) %>
      <%= link_to "delete", activity, method: :delete,
                                      data: { confirm: "You sure?" } %>
      <%= link_to "edit", edit_activity_path(activity) %>
      <% end %>
  </span>
</li>

app/views/activities/edit.html.erb
<% provide(:title, "Edit activity") %>
<div class="row">
	<aside class="col-md-4">
		<section class="farmer_info">
			<%= render 'shared/farmer_info' %>
		</section>
		<section class="activity_form">
			<%= render 'shared/activity_form' %>
		</section>
	</aside>
</div>